version: "3.9"

services:
  r-dev:
    build:
      context: ..
      dockerfile: .devcontainer/r/Dockerfile
    volumes:
      - ..:/workspaces/project:cached
      - renv_cache:/opt/renv/cache
      - ${SECURE_DATA_DIR:-}:/secure-data:ro
    working_dir: /workspaces/project
    command: sleep infinity

  py-dev:
    build:
      context: ..
      dockerfile: .devcontainer/py/Dockerfile
    volumes:
      - ..:/workspaces/project:cached
      - ${SECURE_DATA_DIR:-}:/secure-data:ro
    working_dir: /workspaces/project
    command: sleep infinity

volumes:
  renv_cache:
  poetry_cache:
  pip_cache:

